SNSKBbDOHBTHASOBbDHTCBK-CBTDUNWSNHInISOB@KHPHAIBHICUBFJTBDOHBTHASOBWFTSCFIDBPNSOSOBWUBTBIS	nITWNUBCE^SOBQNEUFISTS^KBHASOBT	-WUHJWSbIBU@BSNDT^ISOPFQBEBFSQNEUFISTT^ISOT@UHHQ^EFTTKNIBDFSDO^JBKHC^CFIDBFEKBUO^SOJRWKNASNI@JHHCJFKBQHDFKPNSOFTJHHSOUBSUHAKFNU-DHQBUfUSwUHJWSiBHI
KNSDNS^TDFWBPNSOUBSUH
ARSRUNTSNDDFUT]HHJNI@E^QNEUFISDHKHUTTKBBLTFBTSOBSNDC^IFJNDDHJWHTNSNHI@KHPNI@BKBJBIST-TA_T^ISOFUWB@@NHTQNISF@BCURJJFDONIBEBFSTTRESKBQNI^KDUFDLKBFJENBISDNS^THRICT-QHDFKTJFKBQHDFKTJHHSOFICTHRKARKPNSOFONISHAIHTSFK@NF-QHDFKTtSURDSRUBCUBSUHWHWSUFDLPNSOFTSUHI@NISUHFICFDFSDO^HRSUHNIDKRCNI@JBJHUFEKBOHHLTPNSOJFKBQHDFK-LB^PHUCTT^ISOPFQBUBSUHPFQBTBKBDSUHWHWIHTSFK@NFCFIDBUBSUHQNISF@BDNS^QNEBTsHI^dFTHuRIsHjB-DHCBiFJBNI@R-EWJ-@BIUBnIWRS-WUHJWSnIWRSsUFDLNITWNUBCE^sHI^dFTH
uRIsHjB	rTBTNJNKFUJRTNDFKQNEBJHHCTS^KB@BIUBNITSURJBIST	-KBSSBU-NIDKRCBqHDFKaFKTB-FWWqBUTNHIQ-CRUFSNHI--K^UNDT|NISUH
iBHI`KHPz-HHHHHH-NNNNN--|QBUTB
bKBDSUNDwRKTBz-dFJNIHTCBKR]THJEUFTCBKF^BU-kFTDFKKBTOFEKFIRIBDHBIBKFNUB--|wUB
dOHURT
tHINDpFQBz-PHHHHHHH-uBTWKFICHUCBTRBä–HTTBTNBISBBKDFKHU-eFNKFIKFTJBJHUNFTBIDFCFUNIDä”I--|dOHURT
bDOHBTHASOBz-HHHHHHNNNNN-dHUUBOFDNFJäŠBIBKSNBJWHWBUCNCH-HHHHHHNNNNN-tRBä–HTCBIBä”IRICBTSNIHDHJWFUSNCH--|eUNC@B
uBSUHcUBFJz-bIBKUBTWKFICHUWBUCNCHTBTSFJHT-HHHHHH-qHDBTCBKWFTFCHMRISHTDFISFJHT--|HRSUH
aFCNI@kN@OSTz-HHHHHH-NNNNNN--dUBFSBCE^fswKF^BU-OSSWTPPP	FSWKF^BU	DHJ--dHW^UN@OSåŽfLSNTnID	