PMPHAiAHEJGLKH]pVEMJoAVAPEiAHEJOKHMW.@AWGVMTPMKJeNKQVJA]PLVKQCLPMIA
pLAPVEMJKBAIKPMKJWGEVV]MJCSLMWTAVWKBPLATEWP
mJWTMVA@F]PLAWP]HAKBwPAAHLAEVP
.TVKITPtKSAVBQHVKGOFEHHE@WKEVMJCCQMPEVWKHKWAIKPMKJEHTMEJKIAHK@MAW@]JEIMG@VQITEPPAVJWTEWWMKJEPAIEHARKGEHMJPAJWAEJ@LAEVPBAHPEPIKWTLAVA.GKRAVeVPtVKITPeRMJPECAWPAEIPVEMJQJ@AVEPSMHMCLPWO]WQVVKQJ@A@F]WSMVHMJCIMWPRMRM@FHQALQAW@VEIEPMGEJ@GMJAIEPMGWP]HACHKSMJCHMCLPWEWAJWAKBI]WPAV]EJ@JKWPEHCME.WB\PVEMJSLMWPHAAGLKAWVL]PLIMGVEMHGHEPPAV@MWPEJPPLQJ@AVWKBPSMJ@CQWPW.RKGEHWIEHARKGEHTKSAVBQHEJ@AIKPMRASMPLEPKQGLKBRQHJAVEFMHMP].RKGEHWwPVQGPQVA@VKGOFEHHE@PVEGOSMPLEWPVKJCMJPVKEJ@IKRMJCKQPVKMJGHQ@MJCWKEVMJCCQMPEVWKHKWSMPLTEWWMKJEPAIEHARKGEH.OA]SKV@WVKGOFEHHE@GHEWWMGVKGOWKBPVKGOLAEVPBAHPAIKPMKJEHCQMPEVTMEJKGMJAIEPMGJKWPEHCMGwPAAHLAEVP.GK@AjEIAi]WPAV]KBPLAfHQApVEMJ.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]wLAWcKJA	wPAAHLAEVP
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAVi.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGW..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
