PMPHAgEIMJKWgKJRAVCAJPAWgEIMJKWgKJRAVCAJPAW.@AWGVMTPMKJeOJMCLPWUQAWPJKPBKVHKRAFQPBKVWKQJ@
eJE@RAJPQVAMJVL]PLISLAVAARAV]FAEPMWEJASTEPLARAV]IAHK@]E@MWGKRAV]
mJBHQAJGA@F]wKJM@KrEVME@KWA\TEJWMRAWKJMGPETAWPV]PLMWPVEGOA\THKVAWPLALAEVPKBBQWMKJ
.TVKITP`]JEIMGhEPMJtKT	bQWMKJPVEGOBAEPQVMJCERMFVEJPFHAJ@KBgQIFMEvACCEAPKJwEHWEEJ@iAVAJCQAMJBHQAJGAWSMPLE@VMRMJCPVKTMGEHLKQWAFAEPTVKIMJAJPFVEWWWAGPMKJW@AATW]JPLFEWWHMJAWEJ@MJPVMGEPATAVGQWWMKJ
mJGKVTKVEPAQJA\TAGPA@IAHK@MGWLMBPWEJ@AJAVCAPMG@VKTW
aJAVCAPMGIEHAEJ@BAIEHARKGEHWSMPLTHE]BQHE@	HMFW
.GKRAVeVPtVKITPeFWPVEGPCAKIAPVMGWLETAWIKVTLMJCEJ@GKJRAVCMJCMJEBQPQVMWPMGQVFEJHEJ@WGETAMHHQIMJEPA@F]JAKJHMCLPWEJ@LKHKCVETLMGTVKNAGPMKJW
`MCMPEH@EPEWPVAEIWBHKSPLVKQCLPLAWGAJAGVAEPMJCEWAJWAKBGKJWPEJPIKRAIAJPEJ@PVEJWBKVIEPMKJ
wHAAOTKHMWLA@EJ@L]TAV	IK@AVJEAWPLAPMGSMPLRMFVEJPGKHKVCVE@MAJPW
.WB\vL]PLIMGTAVGQWWMRALMPWW]JPLVMWAVWHEWAV^ETWGVKS@IQVIQVW@MCMPEHCHMPGLAWPVKTMGEHFMV@GEHHWFVEWWWPEFW
.RKGEHWaJAVCAPMGIEHAEJ@BAIEHARKGEHWSMPLERMFVEJPhEPMJBHEMV
.RKGEHWwPVQGPQVA@hEPMJ@EJGAPVEGOSMPLERMFVEJPMJPVKBAEPQVMJCEFQMH@	QTKB@MRAVWAMJWPVQIAJPWEJ@EJA\THKWMRAKQPVKMJGHQ@MJCIQHPMTHACAJVAWLMBPWEJ@TAVGQWWMRA@VKTWSMPL@]JEIMGIEHAEJ@BAIEHARKGEHWPLEPSAERAPLVKQCLPLAMJPVMGEPAVL]PLI
.OA]SKV@WHEPMJTKTBQWMKJGQIFMEVACCEAPKJWEHWEIAVAJCQAPVKTMGEHLKQWA@EJGATKTBMAWPEAJAVCAPMG@EJGAQTFAEPRMFVEJPAPVKTMGEHwKJM@KrEVME@KWKQJ@PVEGOKWPGMJAIEPMG.GK@AjEIA}REMJKVpLAoJMCLPKBPLAhMKJ.FTI.CAJVAmJTQP.TVKITPmJTQPpVEGOMJWTMVA@F]wKJM@KrEVME@K	iM\`ApK@KqJtKGK‘ª∞ÅiANKVAWgEJGMKJAWrEVME@EWXhKiEWaWGQGLE@K`AHiKIAJPK
qWAWMIMHEVIQWMGEHRMFAIKK@WP]HACAJVAMJWPVQIAJPW
.HAPPAV}.MJGHQ@ArKGEHbEHWA.ETTrAVWMKJR.@QVEPMKJ..H]VMGW..gVAEPA@F]eptHE]AV.LPPTWSSS
EPTHE]AV
GKI..gKT]VMCLPÊçeOPMWmJG
