LQLT]oPQKH]JKW^LP]p]YJL2\]K[JQHLQWVqVLP]JWTTQV_UWWJKTWN]OPQKH]JKKW^LTA][PWQV_LP]LQU]T]KKZWV\qVKHQJ]\ZALP][TYKKQ[LYT]W^TWN]YV\TWV_QV_OQLPYUW\]JVUMKQ[YTLOQKL2HJWUHL}UWLQWVYTZYTTY\JQ[PWJ[P]KLJYLQWVKUWWLPY[WMKLQ[_MQLYJKWMT^MTUYT]NW[YTP]YJL^]TLU]TW\Q]KTMKPKLJQV_K]NW[YLQN]HQYVW_]VLT]H]J[MKKQWVJWUYVLQ[YV\VWKLYT_Q[UWW\2[WN]JyJLhJWUHLyK]J]V]TYV\K[YH]YLKMVK]L\J]YUAPM]KW^WJYV_]YV\HQVSKW^L^W[MKOQLPYTWV]^Q_MJ]KLYV\QV_ZAYLJYVIMQTTYS]UW\]JVYV\[QV]UYLQ[KLAT]H]Y[]^MTYV\QVLJWKH][LQN]2K^@_]VLT]OQV\JMKLTQV_KW^LTYS]OYN]K\QKLYVLZQJ\KWV_OYJUYUZQ]VL][PW]K2NW[YTKUYT]NW[YT]UWLQWVYTYV\KWMT^MTOQLPL]V\]JPYJUWVQ]KKUWWLP\]TQN]JA2NW[YTKkLJM[LMJ]\HWHZYTTY\LJY[SOQLP_]VLT]QVLJWYV\P]YJL^]TLWMLJWQV[TM\QV_K]YUT]KKLJYVKQLQWVKOQLPKWMT^MTUYT]NW[YT2S]AOWJ\KZYTTY\JWUYVLQ[Y[WMKLQ[KWMT^MT[QV]UYLQ[VWKLYT_Q[HWH]UWLQWVYTP]YJL^]TLWJ[P]KLJYTUW\]JV[TYKKQ[QVLJWKH][LQN]2[W\]vYU]oMLP]JQV_p]Q_PLK2ZHU
2_]VJ]qVHML2HJWUHLqVHMLlJY[SQVKHQJ]\ZAtMB[YLWTQ[Y

Dv]OpQV\QkWV_Dz]KLW^yJQRQLkQV_PrMZQVvYMLQAYTyLQ^yKTYU|YJKPYVjYNYTÈ§ª®mK]KQUQTYJUMKQ[YTNQZ]UWW\KLAT]_]VJ]QVKLJMU]VLK2T]LL]Jo2QV[TM\]nW[YT~YTK]2YHHn]JKQWVN

	2\MJYLQWV	
22TAJQ[K22{J]YL]\ZAylhTYA]J2PLLHKOOOYLHTYA]J[WU22{WHAJQ_PLú‘

ySLQKqV[